# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build_and_deploy:
    executor: node/default
    steps:
      - checkout
      - run:
          command: npm install
          name: Install dependencies
      - run:
          command: npm i -g next
          name: Install nextjs
      - run:
          command: next build
          name: Build with nextjs
      - run:
          command: next export
          name: Export
      - deploy:
          name: Deploy as static page to github pages.
          command: |
            if [ "${CIRCLE_BRANCH}" = "main"]; then
              echo -e "Deploying to github pages...\n"
              cd ~/repo
               git config --global user.email "builds@circleci.com"
              git config --global user.name "CircleCI"
              git clone --quiet --branch=$CIRCLE_BRANCH https://${GH_TOKEN}@github.com/$TARGET_REPO built_website > /dev/null
              echo "Installing rsync"
              sudo apt-get -y install rsync
              cd built_website
              echo "rsync built code with checked out code..."
              rsync -r --exclude=.git --delete ../$PELICAN_OUTPUT_FOLDER/ ./
              echo "add files to git..."
              git add -f .
              echo "commit files to git repository..."
              if git commit -m "CircleCI build $CIRCLE_BUILD_NUM pushed to Github Pages" ; then
                echo "git push files with force..."
                git push -fq origin $BRANCH > /dev/null
                echo -e "Deploy completed\n"
              else
                echo "Content not changed, nothing to deploy"
              fi
            else
              echo "Not master branch, dry run only"
            fi
workflows:
  version: 2
  deploy:
    jobs:
      - build_and_deploy